# Generated by Django 3.2.4 on 2021-08-01 03:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ForexQuote',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'currency_from',
                    models.CharField(max_length=5, verbose_name='currency converting from'),
                ),
                (
                    'currency_to',
                    models.CharField(max_length=5, verbose_name='currency converting to'),
                ),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=19)),
                (
                    'bid_price',
                    models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
                ),
                (
                    'ask_price',
                    models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
                ),
                (
                    'created_at',
                    models.DateTimeField(db_index=True, editable=False, verbose_name='created at'),
                ),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
