# Generated by Django 3.2.4 on 2021-08-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forexquote',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='created at'),
        ),
    ]
